# Generated by Django 3.0.5 on 2020-04-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200408_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pallet_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
